version: "3.9"

services:
  core:
    image: maximking19/wasicdn-core
    build: .
    network_mode: host
    env_file: .env # Create a .env file and add Slave Locations.
    environment:
      - name=Core
      - mongodb="mongodb://" # Your MongoDB Connector For The User & Files Database
      - PORT=3001 # The Port For The CDN Service
      - adminPort=3010 # The Admin Port (For Backend Socket.io Use Only)
      - adminPassword="yg6g4byugeuybygbiygyugbyuftuftufvtufvtfytdfcytftufytfc"
      - files="local" # "s3" or "local", Where the CDN files are downloaded from. (Local = Pulls From The Core Server Uploads Folder, S3 = Pulls From The S3 Bucket)
      - defaultServer="DOMAIN_HERE" # The Fallback IP If There Isnt a Close Server
    # s3 Bucket Details (If using s3)
      - s3Provider="" # Amazon AWS S3 "aws", Google Cloud Storage "gcs", Microsoft Azure Blob Storage "azure", DigitalOcean Spaces "digitalocean", Wasabi Object Storage "wasabi" (Custom S3 Bucket use = "s3compatible")
    # - endpoint="" # If using "s3compatible", add endpoint here
    # - region="" # If using "aws" or "digitalocean"
      - accessKeyID=""
      - secretAccessKey=""
      - bucketName=""
    volumes:
      - /usr/lib/cdn-core/uploads:/usr/src/CDN/core/uploads # Where the uploads are stored (/host/path:/container/path)
    ports:
      - "3001:3001" # Change this to PORT Variable
      - "3010:3010" # Change this to adminPort Variable