version: "3.9"

services:
  cdn:
    image: maximking19/wasicdn-slave
    build: .
    network_mode: host
    environment:
      - PORT=3005 # The Port For The CDN
      - adminPassword="yg6g4byugeuybygbiygyugbyuftuftufvtufvtfytdfcytftufytfc"
      - mongodb="mongodb://" # Your MongoDB Connector For The User & Files Database
      - files="local" # "s3" or "local", Where the CDN files are downloaded from. (Local = Pulls From The Core Server Uploads Folder, S3 = Pulls From The S3 Bucket)
      - coreServerIP="localhost:3001" # Where the core server is located (IP:PORT) (Can Find Port in Docker Compose Core Config)
      - discordWebhook="https://discord.com/webhook/" # Discord Webhook For Files Uploads and User Audit Logs
      # s3 Bucket Details (If using s3)
      - s3Provider="" # Amazon AWS S3 "aws", Google Cloud Storage "gcs", Microsoft Azure Blob Storage "azure", DigitalOcean Spaces "digitalocean", Wasabi Object Storage "wasabi" (Custom S3 Bucket use = "s3compatible")
    # - endpoint="" # If using "s3compatible", add endpoint here
    # - region="" # If using "aws" or "digitalocean"
      - accessKeyID=""
      - secretAccessKey=""
      - bucketName=""
    volumes:
      - /usr/lib/cdn-slave/uploads:/usr/src/CDN/slave/uploads # Where the uploads are stored (/host/path:/container/path)