version: "3.9"

services:
  cdn:
    build: .
    network_mode: host
    environment:
      - mongodb='mongodb://' # Your MongoDB Connector For The User & Files Database
      - PORT=3005 # The Port For The CDN
      - 
